routes/web.php
<?php

/**
 * Admin Routes.
 */
Route::group(['namespace' => 'Admin', 'as' => 'admin.'], function () {

    // Authentication Required Routes
    Route::group(['middleware' => 'auth'], function () {

        //dashboard
        Route::get('/', 'Dashboard\IndexController')
            ->name('dashboard.index');

        // Companies
        Route::group(['prefix' => 'companies', 'namespace' => 'Companies', 'as' => 'company.'], function () {

            Route::get('', 'CompaniesIndexController')
                ->name('index');

            Route::get('create', 'CreateCompanyIndexController')
                ->name('create');

            Route::post('store', 'StoreCompanyController')
                ->name('store');

            Route::get('{company:name}/edit', 'EditCompanyIndexController')
                ->name('edit');

            Route::post('{company}/update', 'UpdateCompanyController')
                ->name('update');

            Route::get('{company:name}/details', 'ShowCompanyController')
                ->name('details');

            Route::delete('{company}/delete', 'DeleteCompanyController')
                ->name('delete');
        });

        // Products
        Route::group(['prefix' => 'products', 'namespace' => 'Products', 'as' => 'product.'], function () {

            Route::get('', 'ProductsIndexController')
                ->name('index');

            Route::get('create', 'CreateProductIndexController')
                ->name('create');

            Route::post('store', 'StoreProductController')
                ->name('store');

            Route::get('{product:name}/edit', 'EditProductIndexController')
                ->name('edit');

            Route::post('{product}/update', 'UpdateProductController')
                ->name('update');

            Route::get('{product:name}/details', 'ShowProductController')
                ->name('details');

            Route::delete('{product}/delete', 'DeleteProductController')
                ->name('delete');
        });
    });

    // Auth Routes
    Route::group(['prefix' => 'auth', 'namespace' => 'Auth', 'as' => 'auth.'], function () {
        Route::get('login', 'LoginIndexController')
            ->name('login.index')
            ->middleware('guest');

        Route::post('login', 'PostLoginController')
            ->name('login.post')
            ->middleware('guest');

        Route::get('logout', 'LogoutController')
            ->name('logout')
            ->middleware('auth');
    });
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Hash;

class Company extends Authenticatable
{
    use HasFactory;

    const STATUS_ACTIVE = 1;

    const STATUS_INACTIVE = 2;

    const AVAILABLE_STATUSES = [
        self::STATUS_ACTIVE => 'active',
        self::STATUS_INACTIVE => 'inactive',
    ];

    const STATUSES_BADGES = [
        self::STATUS_ACTIVE => 'badge-success',
        self::STATUS_INACTIVE => 'badge-danger',
    ];
    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name', 'email', 'password', 'remember_token', 'tel', 'address', 'subdomain', 'status'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];


    /**
     * Relations
     */
    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }

    public function loginLogs(): HasMany
    {
        return $this->hasMany(CompanyLoginLog::class);
    }

    /**
     * Scopes
     *
     * @param $query
     * @param $value
     *
     * @return mixed
     */

    public function scopeTextSearch($query, $value)
    {
        $searchable_columns = ['name', 'subdomain', 'email'];
        return $query->when($value, function ($q) use ($value, $searchable_columns) {
            foreach ($searchable_columns as $column) {
                $q->orWhere($column, "like", "%$value%");
            }
        });
    }

    /**
     * Accessors
     */

    public function getFormattedStatusAttribute(): string
    {
        return self::AVAILABLE_STATUSES[$this->status];
    }

    public function getStatusBadgeAttribute(): string
    {
        return self::STATUSES_BADGES[$this->status];
    }


    /**
     * Mutators
     */

    /**
     * @param $value
     */
    public function setSubdomainAttribute($value): void
    {
        $this->attributes['subdomain'] = strtolower($value);
    }

    /**
     * @param $value
     */
    public function setPasswordAttribute($value): void
    {
        if ($value) {
            if (strpos($value, '$2y$') !== 0) {
                $this->attributes['password'] = bcrypt($value);
            } else {
                $this->attributes['password'] = $value;
            }
        }
    }
}

app/Http/Controllers/Admin/Companies/CompaniesIndexController.php
<?php

namespace App\Http\Controllers\Admin\Companies;

use App\Http\Controllers\Controller;
use App\Models\Company;

class CompaniesIndexController extends Controller
{
    public function __invoke()
    {
        $search_value = request()->get('q');
        $companies = Company::textSearch($search_value)
            ->latest('id')
            ->paginate(15, ['id', 'name', 'subdomain', 'status'])
            ->withQueryString();
        return view('pages.companies.index', compact('companies', 'search_value'));
    }
}

app/Http/Controllers/Admin/Companies/CreateCompanyIndexController.php
<?php

namespace App\Http\Controllers\Admin\Companies;

use App\Http\Controllers\Controller;
use App\Models\Company;

class CreateCompanyIndexController extends Controller
{
    public function __invoke()
    {
        $statuses = Company::AVAILABLE_STATUSES;
        return view('pages.companies.create', compact('statuses'));
    }
}

app/Http/Controllers/Admin/Companies/DeleteCompanyController.php
<?php

namespace App\Http\Controllers\Admin\Companies;

use App\Http\Controllers\Controller;
use App\Models\Company;

class DeleteCompanyController extends Controller
{
    public function __invoke(Company $company)
    {
        $company->delete();
        return redirect()->route('admin.company.index')->withSuccess('Deleted Successfully');
    }
}

app/Http/Controllers/Admin/Companies/EditCompanyIndexController.php
<?php

namespace App\Http\Controllers\Admin\Companies;

use App\Http\Controllers\Controller;
use App\Models\Company;

class EditCompanyIndexController extends Controller
{
    public function __invoke(Company $company)
    {
        $statuses = Company::AVAILABLE_STATUSES;
        return view('pages.companies.edit', compact('company', 'statuses'));
    }
}

app/Http/Controllers/Admin/Companies/ShowCompanyController.php
<?php

namespace App\Http\Controllers\Admin\Companies;

use App\Http\Controllers\Controller;
use App\Models\Company;

class ShowCompanyController extends Controller
{
    public function __invoke(Company $company)
    {
        $company->loadCount('products');
        return view('pages.companies.details', compact('company'));
    }
}

app/Http/Controllers/Admin/Companies/StoreCompanyController.php
<?php

namespace App\Http\Controllers\Admin\Companies;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Companies\StoreCompanyRequest;
use App\Models\Company;

class StoreCompanyController extends Controller
{
    public function __invoke(StoreCompanyRequest $request)
    {
        Company::create($request->validated());
        return redirect()->route('admin.company.index')->withSuccess('Added Successfully');
    }
}

app/Http/Controllers/Admin/Companies/UpdateCompanyController.php
<?php

namespace App\Http\Controllers\Admin\Companies;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Companies\UpdateCompanyRequest;
use App\Models\Company;

class UpdateCompanyController extends Controller
{
    public function __invoke(Company $company, UpdateCompanyRequest $request)
    {
        $company->update($request->validated());
        return redirect()->route('admin.company.index')->withSuccess('Updated Successfully');
    }
}

app/Http/Controllers/Companies/HomePage/IndexController.php
<?php

namespace App\Http\Controllers\Companies\HomePage;

use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    public function __invoke()
    {
        $user = auth('company')->user();
        $user->loadCount('products');
        return view('tenant.pages.profile.index', compact('user'));
    }
}

resources/views/pages/companies/create.blade.php
@extends('layouts.main')
@section('content')
    <section class="content mb-1">
        <form action="{{route('admin.company.store')}}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Company Name</label>
                                <input type="text" id="inputName" value="{{old('name')}}" name="name" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputPhone">Phone</label>
                                <input type="number" id="inputPhone" value="{{old('tel')}}" name="tel" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputDescription">Address</label>
                                <textarea id="inputDescription" class="form-control" rows="4" name="address"
                                          required>{{old('address')}}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="inputStatus">Status</label>
                                <select id="inputStatus" class="form-control custom-select" name="status" required>
                                    @foreach($statuses as $value=>$label)
                                        <option
                                                value="{{$value}}"
                                                {{old('status') == $value ? 'selected' : '' }}>
                                            {{ucwords($label)}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="inputSubdomain">Subdomain</label>
                                <input type="text" id="inputSubdomain" name="subdomain" required class="form-control"
                                       value="{{old('subdomain')}}">
                                <small>must be one word without any spaces or special characters</small>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail">Email</label>
                                <input type="email" id="inputEmail" name="email" required class="form-control"
                                       value="{{old('email')}}">
                            </div>
                            <div class="form-group">
                                <label for="inputPassword">Password</label>
                                <input type="password" id="inputPassword" name="password" required class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputPasswordConfirmation">Password Confirmation</label>
                                <input type="password" id="inputPasswordConfirmation" name="password_confirmation"
                                       required
                                       class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="{{route('admin.company.index')}}" class="btn btn-secondary">Cancel</a>
                    <button type="submit" class="btn btn-success float-right" dusk="submit-button"> Create new </button>
                </div>
            </div>
        </form>
    </section>
@stop

resources/views/pages/companies/details.blade.php
@extends('layouts.main')

@section('content')
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-12 order-2 order-md-1">
                        <div class="row">
                            <div class="col-12 col-sm-12">
                                <div class="info-box bg-light">
                                    <div class="info-box-content">
                                        <span class="info-box-text text-center text-muted">Products Count</span>
                                        <span class="info-box-number text-center text-muted mb-0">{{number_format($company->products_count)}}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 ">
                                <h3 class="text-primary"><i class="fas fa-building"></i> {{$company->name}}</h3>
                                <p class="text-muted">{{$company->address}}</p>
                                <br>
                                <div class="text-muted">
                                    <p class="text-sm">Subdomain
                                        <b class="d-block">{{$company->subdomain}}</b>
                                    </p>
                                    <p class="text-sm">Phone
                                        <b class="d-block">{{$company->tel}}</b>
                                    </p>
                                    <p class="text-sm">Email
                                        <b class="d-block">{{$company->email}}</b>
                                    </p>
                                    <p class="text-sm">Status
                                        <b class="d-block"><span class="badge {{$company->status_badge}}">{{$company->formatted_status}}</span></b>
                                    </p>
                                    <p class="text-sm">Creation Date
                                        <b class="d-block">{{$company->created_at->toDateTimeString()}}</b>
                                    </p>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-12">
                        <a href="{{route('admin.company.index')}}" class="btn btn-secondary float-right">Back</a>
                    </div>
                </div>
            </div>
        </div>

    </section>
@stop

resources/views/pages/companies/edit.blade.php
@extends('layouts.main')
@section('content')
    <section class="content mb-1">
        <form action="{{route('admin.company.update',$company)}}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Company Name</label>
                                <input type="text" id="inputName" value="{{old('name') ?? $company->name}}" name="name"
                                       required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputPhone">Phone</label>
                                <input type="number" id="inputPhone" value="{{old('tel') ?? $company->tel}}" name="tel"
                                       required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputDescription">Address</label>
                                <textarea id="inputDescription" class="form-control" rows="4" name="address"
                                          required>{{old('address') ?? $company->address}}</textarea>
                            </div>

                            <div class="form-group">
                                <label for="inputStatus">Status</label>
                                <select id="inputStatus" class="form-control custom-select" name="status" required>
                                    @foreach($statuses as $value=>$label)
                                        <option
                                                value="{{$value}}"
                                                {{(old('status') || $company->status == $value) ? 'selected' : ''}}>
                                            {{ucwords($label)}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="inputSubdomain">Subdomain</label>
                                <input type="text" id="inputSubdomain" name="subdomain" required class="form-control"
                                       value="{{old('subdomain') ?? $company->subdomain}}">
                                <small>must be one word without any spaces or special characters</small>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail">Email</label>
                                <input type="email" id="inputEmail" name="email" required class="form-control"
                                       value="{{old('email') ?? $company->email}}">
                            </div>
                            <div class="form-group">
                                <label for="inputPassword">Password</label>
                                <input type="password" id="inputPassword" name="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputPasswordConfirmation">Password Confirmation</label>
                                <input type="password" id="inputPasswordConfirmation" name="password_confirmation"
                                       class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="{{route('admin.company.index')}}" class="btn btn-secondary">Cancel</a>
                    <button type="submit" class="btn btn-success float-right" dusk="submit-button"> Update</button>
                </div>
            </div>
        </form>
    </section>
@stop

resources/views/pages/companies/index.blade.php
@extends('layouts.main')
@section('content')

    <section class="content">
        <div class="row mb-2 justify-content-between">
            <div class="col-md-4 ">
                <form>
                    <div class="input-group">
                        <input type="search" name="q" value="{{$search_value}}"  class="form-control form-control-lg"
                               placeholder="Type your keywords here">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-lg btn-default" dusk="submit-search">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-2">
                <a href="{{route('admin.company.create')}}" type="button" dusk="create" class="btn btn-block btn-primary">Create</a>
            </div>
        </div>

        <div class="card">
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th style="width: 20%">
                            Company Name
                        </th>
                        <th style="width: 30%">
                            Subdomain
                        </th>
                        <th style="width: 8%" class="text-center">
                            Status
                        </th>
                        <th style="width: 20%">
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($companies as $company)
                        <tr>
                            <td>
                                {{$company->id}}
                            </td>
                            <td>
                                <a>
                                    {{$company->name}}
                                </a>
                            </td>
                            <td>
                                {{$company->subdomain}}
                            </td>
                            <td class="project-state">
                                <span class="badge {{$company->status_badge}}">{{$company->formatted_status}}</span>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="{{route('admin.company.details',$company)}}" dusk="view">
                                    <i class="fas fa-folder">
                                    </i>
                                    View
                                </a>
                                <a class="btn btn-info btn-sm" href="{{route('admin.company.edit',$company)}}" dusk="edit">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Edit
                                </a>
                                <button class="btn btn-danger btn-sm delete-row" data-name="{{$company->name}}"
                                        dusk="delete"
                                        data-url="{{route('admin.company.delete',$company)}}">
                                    <i class="fas fa-trash">
                                    </i>
                                    Delete
                                </button>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
                <div class="float-right m-2">
                    {{$companies->links()}}
                </div>
            </div>
        </div>
    </section>
    <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="" method="post" id="delete-form">
                    @method('delete')
                    @csrf
                    <div class="modal-header">
                        <h4 class="modal-title">Delete Confirmation</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p class="text-bold">
                            Are you sure you want to delete <span id="modal-text" class="text-danger"></span> ?

                            this action cant be reverted !
                        </p>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger" dusk="delete-button">Delete</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
@stop

@push('scripts')
    <script>
        $('.delete-row').click(function (e) {
            e.preventDefault();
            let url = $(this).data('url');
            let name = $(this).data('name');
            $('#modal-text').html(name)
            $('#delete-form').attr('action', url)
            $('#modal-default').modal('show')
        })
    </script>
@endpush