routes/web.php
<?php

/**
 * Admin Routes.
 */
Route::group(['namespace' => 'Admin', 'as' => 'admin.'], function () {

    // Authentication Required Routes
    Route::group(['middleware' => 'auth'], function () {

        //dashboard
        Route::get('/', 'Dashboard\IndexController')
            ->name('dashboard.index');

        // Companies
        Route::group(['prefix' => 'companies', 'namespace' => 'Companies', 'as' => 'company.'], function () {

            Route::get('', 'CompaniesIndexController')
                ->name('index');

            Route::get('create', 'CreateCompanyIndexController')
                ->name('create');

            Route::post('store', 'StoreCompanyController')
                ->name('store');

            Route::get('{company:name}/edit', 'EditCompanyIndexController')
                ->name('edit');

            Route::post('{company}/update', 'UpdateCompanyController')
                ->name('update');

            Route::get('{company:name}/details', 'ShowCompanyController')
                ->name('details');

            Route::delete('{company}/delete', 'DeleteCompanyController')
                ->name('delete');
        });

        // Products
        Route::group(['prefix' => 'products', 'namespace' => 'Products', 'as' => 'product.'], function () {

            Route::get('', 'ProductsIndexController')
                ->name('index');

            Route::get('create', 'CreateProductIndexController')
                ->name('create');

            Route::post('store', 'StoreProductController')
                ->name('store');

            Route::get('{product:name}/edit', 'EditProductIndexController')
                ->name('edit');

            Route::post('{product}/update', 'UpdateProductController')
                ->name('update');

            Route::get('{product:name}/details', 'ShowProductController')
                ->name('details');

            Route::delete('{product}/delete', 'DeleteProductController')
                ->name('delete');
        });
    });

    // Auth Routes
    Route::group(['prefix' => 'auth', 'namespace' => 'Auth', 'as' => 'auth.'], function () {
        Route::get('login', 'LoginIndexController')
            ->name('login.index')
            ->middleware('guest');

        Route::post('login', 'PostLoginController')
            ->name('login.post')
            ->middleware('guest');

        Route::get('logout', 'LogoutController')
            ->name('logout')
            ->middleware('auth');
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Product extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'price', 'quantity', 'company_id'];

    /**
     * Relations.
     */
    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }


    /**
     * Scopes
     *
     * @param $query
     * @param $value
     *
     * @return mixed
     */

    public function scopeTextSearch(Builder $query, $value)
    {
        $searchable_columns = ['name', 'price', 'quantity'];
        return $query->when($value, function ($q) use ($value, $searchable_columns) {
            foreach ($searchable_columns as $column) {
                $q->orWhere($column, "like", "%$value%");
            }
            $q->orWhereRelation('company', 'name', 'like', "%$value%");
        });
    }
}

app/Http/Controllers/Admin/Products/CreateProductIndexController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Http\Controllers\Controller;
use App\Models\Company;

class CreateProductIndexController extends Controller
{
    public function __invoke()
    {
        $companies = Company::all('id', 'name');
        return view('pages.products.create', compact('companies'));
    }
}

app/Http/Controllers/Admin/Products/DeleteProductController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Http\Controllers\Controller;
use App\Models\Product;

class DeleteProductController extends Controller
{
    public function __invoke(Product $product)
    {
        $product->delete();
        return redirect()->route('admin.product.index')->withSuccess('Deleted Successfully');
    }
}

app/Http/Controllers/Admin/Products/EditProductIndexController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\Product;

class EditProductIndexController extends Controller
{
    public function __invoke(Product $product)
    {
        $companies = Company::all('id', 'name');
        $product->load('company:name');
        return view('pages.products.edit', compact('product', 'companies'));
    }
}

app/Http/Controllers/Admin/Products/ProductsIndexController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\Product;

class ProductsIndexController extends Controller
{
    public function __invoke()
    {
        $search_value = request()->get('q');
        $products = Product::textSearch($search_value)
            ->latest('id')
            ->with(['company:id,name'])
            ->paginate(15)
            ->withQueryString();
        return view('pages.products.index', compact('products', 'search_value'));
    }
}

app/Http/Controllers/Admin/Products/ShowProductController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\Product;

class ShowProductController extends Controller
{
    public function __invoke(Product $product)
    {
        return view('pages.products.details', compact('product'));
    }
}

app/Http/Controllers/Admin/Products/StoreProductController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Products\StoreProductRequest;
use App\Models\Product;

class StoreProductController extends Controller
{
    public function __invoke(StoreProductRequest $request)
    {
        Product::create($request->validated());
        return redirect()->route('admin.product.index')->withSuccess('Added Successfully');
    }
}

app/Http/Controllers/Admin/Products/UpdateProductController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Products\UpdateProductRequest;
use App\Models\Product;

class UpdateProductController extends Controller
{
    public function __invoke(Product $product, UpdateProductRequest $request)
    {
        $product->update($request->validated());
        return redirect()->route('admin.product.index')->withSuccess('Updated Successfully');
    }
}

resources/views/pages/products/create.blade.php
@extends('layouts.main')
@section('content')
    <section class="content mb-1">
        <form action="{{route('admin.product.store')}}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Product Name</label>
                                <input type="text" id="inputName" value="{{old('name')}}" name="name" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputPrice">Price</label>
                                <input type="number" id="inputPrice" value="{{old('price')}}" name="price" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputQuantity">Quantity</label>
                                <input type="number" id="inputQuantity" value="{{old('quantity')}}" name="quantity" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputCompany">Company</label>
                                <select id="inputCompany" class="form-control custom-select" name="company_id" required>
                                    @foreach($companies as $company)
                                        <option
                                                value="{{$company->id}}"
                                                {{old('company_id') == $company->id ? 'selected' : '' }}>
                                            {{$company->name}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="{{route('admin.product.index')}}" class="btn btn-secondary">Cancel</a>
                    <button type="submit" class="btn btn-success float-right"> Create new </button>
                </div>
            </div>
        </form>
    </section>
@stop

resources/views/pages/products/details.blade.php
@extends('layouts.main')

@section('content')
    <section class="content">

        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-12 order-2 order-md-1">
                        <div class="row">
                            <div class="col-12 ">
                                <h3 class="text-primary"><i class="fas fa-box-open"></i> {{$product->name}}</h3>
                                <p class="text-muted"><a href="{{route('admin.company.details',$product->company->name)}}">{{$product->company->name}}</a></p>
                                <br>
                                <div class="text-muted">
                                    <p class="text-sm">Price
                                        <b class="d-block">{{number_format($product->price)}}</b>
                                    </p>
                                    <p class="text-sm">Quantity
                                        <b class="d-block">{{number_format($product->quantity)}}</b>
                                    </p>
                                    <p class="text-sm">Creation Date
                                        <b class="d-block">{{$product->created_at->toDateTimeString()}}</b>
                                    </p>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-12">
                        <a href="{{route('admin.product.index')}}" class="btn btn-secondary float-right">Back</a>
                    </div>
                </div>
            </div>
        </div>

    </section>
@stop

resources/views/pages/products/edit.blade.php
@extends('layouts.main')
@section('content')
    <section class="content mb-1">
        <form action="{{route('admin.product.update',$product)}}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="inputName">Product Name</label>
                                <input type="text" id="inputName" value="{{old('name') ?? $product->name}}" name="name"
                                       required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputPrice">Price</label>
                                <input type="number" id="inputPrice" value="{{old('price') ?? $product->price}}"
                                       name="price" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputQuantity">Quantity</label>
                                <input type="number" id="inputQuantity"
                                       value="{{old('quantity') ?? $product->quantity}}" name="quantity" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="inputCompany">Company</label>
                                <select id="inputCompany" class="form-control custom-select" name="company_id" required>
                                    @foreach($companies as $company)
                                        <option
                                                value="{{$company->id}}"
                                                {{old('company_id') || $product->company_id == $company->id ? 'selected' :''}}>
                                            {{$company->name}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="{{route('admin.product.index')}}" class="btn btn-secondary">Cancel</a>
                    <button type="submit" class="btn btn-success float-right"> Update</button>
                </div>
            </div>
        </form>
    </section>
@stop

resources/views/pages/products/index.blade.php
@extends('layouts.main')
@section('content')

    <section class="content">
        <div class="row mb-2 justify-content-between">
            <div class="col-md-4 ">
                <form>
                    <div class="input-group">
                        <input type="search" name="q" value="{{$search_value}}" class="form-control form-control-lg"
                               placeholder="Type your keywords here">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-lg btn-default">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-2">
                <a href="{{route('admin.product.create')}}" type="button" class="btn btn-block btn-primary">Create</a>
            </div>
        </div>

        <div class="card">
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th style="width: 20%">
                            Product Name
                        </th>
                        <th style="width: 30%">
                            Price
                        </th>
                        <th style="width: 8%" class="text-center">
                            Company
                        </th>
                        <th style="width: 20%">
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)
                        <tr>
                            <td>
                                {{$product->id}}
                            </td>
                            <td>
                                <a>
                                    {{$product->name}}
                                </a>
                            </td>
                            <td>
                                {{number_format($product->price)}}
                            </td>
                            <td class="project-state">
                                <a href="{{route('admin.company.details',$product->company->name)}}">{{$product->company->name}}</a>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="{{route('admin.product.details',$product)}}">
                                    <i class="fas fa-folder">
                                    </i>
                                    View
                                </a>
                                <a class="btn btn-info btn-sm" href="{{route('admin.product.edit',$product)}}">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Edit
                                </a>
                                <button class="btn btn-danger btn-sm delete-row" data-name="{{$product->name}}"
                                        data-url="{{route('admin.product.delete',$product)}}">
                                    <i class="fas fa-trash">
                                    </i>
                                    Delete
                                </button>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
                <div class="float-right m-2">
                    {{$products->links()}}
                </div>
            </div>

        </div>

    </section>
    <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="" method="post" id="delete-form">
                    @method('delete')
                    @csrf
                    <div class="modal-header">
                        <h4 class="modal-title">Delete Confirmation</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p class="text-bold">
                            Are you sure you want to delete <span id="modal-text" class="text-danger"></span> ?

                            this action cant be reverted !
                        </p>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
@stop

@push('scripts')
    <script>
        $('.delete-row').click(function (e) {
            e.preventDefault();
            let url = $(this).data('url');
            let name = $(this).data('name');
            $('#modal-text').html(name)
            $('#delete-form').attr('action', url)
            $('#modal-default').modal('show')
        })
    </script>
@endpush