routes/web.php
<?php

/**
 * Admin Routes.
 */
Route::group(['namespace' => 'Admin', 'as' => 'admin.'], function () {

    // Authentication Required Routes
    Route::group(['middleware' => 'auth'], function () {

        //dashboard
        Route::get('/', 'Dashboard\IndexController')
            ->name('dashboard.index');

        // Companies
        Route::group(['prefix' => 'companies', 'namespace' => 'Companies', 'as' => 'company.'], function () {

            Route::get('', 'CompaniesIndexController')
                ->name('index');

            Route::get('create', 'CreateCompanyIndexController')
                ->name('create');

            Route::post('store', 'StoreCompanyController')
                ->name('store');

            Route::get('{company:name}/edit', 'EditCompanyIndexController')
                ->name('edit');

            Route::post('{company}/update', 'UpdateCompanyController')
                ->name('update');

            Route::get('{company:name}/details', 'ShowCompanyController')
                ->name('details');

            Route::delete('{company}/delete', 'DeleteCompanyController')
                ->name('delete');
        });

        // Products
        Route::group(['prefix' => 'products', 'namespace' => 'Products', 'as' => 'product.'], function () {

            Route::get('', 'ProductsIndexController')
                ->name('index');

            Route::get('create', 'CreateProductIndexController')
                ->name('create');

            Route::post('store', 'StoreProductController')
                ->name('store');

            Route::get('{product:name}/edit', 'EditProductIndexController')
                ->name('edit');

            Route::post('{product}/update', 'UpdateProductController')
                ->name('update');

            Route::get('{product:name}/details', 'ShowProductController')
                ->name('details');

            Route::delete('{product}/delete', 'DeleteProductController')
                ->name('delete');
        });
    });

    // Auth Routes
    Route::group(['prefix' => 'auth', 'namespace' => 'Auth', 'as' => 'auth.'], function () {
        Route::get('login', 'LoginIndexController')
            ->name('login.index')
            ->middleware('guest');

        Route::post('login', 'PostLoginController')
            ->name('login.post')
            ->middleware('guest');

        Route::get('logout', 'LogoutController')
            ->name('logout')
            ->middleware('auth');
    });
});

resources/views/layouts/partials/aside.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <a href="#" class="d-block">{{auth()->user()->name}}</a>
            </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @inject('multiTenant', 'App\Services\MultiTenant')

                @if ($multiTenant::isAdminRoute())
                    <li class="nav-item">
                        <a href="{{route('admin.dashboard.index')}}" class="nav-link">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                Dashboard
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.company.index')}}" class="nav-link">
                            <i class="nav-icon far fa-building"></i>
                            <p>
                                Companies
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.product.index')}}" class="nav-link">
                            <i class="nav-icon fas fa-box-open"></i>
                            <p>
                                Products
                            </p>
                        </a>
                    </li>
                @else
                    <li class="nav-item">
                        <a href="{{route('companies.homepage.index')}}" class="nav-link">
                            <i class="nav-icon far fa-user-circle"></i>
                            <p>
                                Profile
                            </p>
                        </a>
                    </li>
                @endif
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/layouts/partials/auth-layout.blade.php
<body class="hold-transition login-page">
<div class="login-box">

    @yield('content')

</div>

</body>

resources/views/layouts/partials/breadcrumbs.blade.php
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item {{!count(Request::segments()) ? 'active' : ''}}">
                        @if (count(Request::segments()))

                            <a href="{{route('admin.dashboard.index')}}">Home</a>

                        @else
                            Home
                        @endif
                    </li>
                    <?php $link = "" ?>
                    @for($i = 1; $i <= count(Request::segments()); $i++)
                        @if($i < count(Request::segments()) & $i > 0 & $i < 2)
                            <?php $link .= "/" . Request::segment($i); ?>
                            <li class="breadcrumb-item ">

                                <a href="<?= $link ?>">{{ ucwords(str_replace('-',' ',Request::segment($i)))}}</a>

                            </li>
                        @else

                            <li class="breadcrumb-item active">{{ucwords(str_replace('-',' ',Request::segment($i)))}}</li>

                        @endif
                    @endfor
                </ol>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/partials/default-layout.blade.php
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    @include("layouts.partials.navigation")

    @include("layouts.partials.aside")


    <div class="content-wrapper">

        @include('layouts.partials.breadcrumbs')

        @yield('content')

    </div>

    @include('layouts.partials.footer')

</div>

</body>

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2014-{{now()->year}} <a href="https://khtwah.com/">khtwah.com</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.0
    </div>
</footer>

resources/views/layouts/partials/navigation.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->

        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        @inject('multiTenant', 'App\Services\MultiTenant')
        <li class="nav-item">
            <a class="nav-link" href="{{$multiTenant->isAdminRoute() ?  route('admin.auth.logout') :route('companies.auth.logout')}}" role="button">
                <i class="fas fa-sign-out-alt"></i>
            </a>
        </li>
    </ul>
</nav>